# Build stage
FROM golang:1.23.2-alpine AS builder

WORKDIR /app

# Copy source code
COPY ./ ./

# Install dependencies required for building
RUN apk add --update --no-cache git make

# Build the application
RUN make build-auth

# Final stage
FROM alpine:latest

WORKDIR /app

# Copy files
COPY --from=builder /app/bin/sm4-auth ./
COPY --from=builder /app/version ./version
COPY --from=builder /app/keys/private.pem ./keys/private.pem
COPY --from=builder /app/keys/public.pem ./keys/public.pem

# Add /app to PATH
ENV PATH="/app:${PATH}"

# Expose port 50051
EXPOSE 50051

# Start the application
CMD ["./sm4-auth"]
