# Build stage
FROM golang:1.24-alpine AS builder

WORKDIR /app

# Copy source code
COPY ./ ./

# Install dependencies required for building
RUN apk add --update --no-cache git make

# Build the application
RUN make build-worker

# Final stage
FROM alpine:latest

WORKDIR /app

# Copy files
COPY --from=builder /app/bin/sm4-worker ./
COPY --from=builder /app/version ./version

# Add /app to PATH
ENV PATH="/app:${PATH}"

# Start the application
CMD ["./sm4-worker"]
