apiVersion: batch/v1
kind: CronJob
metadata:
  name: sm4-db-backup
spec:
  schedule: "0 0 * * *"  # Schedule to run daily at 00:00
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: sm4-db-backup
              image: postgres:17.0-alpine
              env:
                - name: PGPASSWORD
                  value: "postgres"
              command: [ "/bin/sh", "-c" ]
              args:
                - "pg_dump -h sm4-db -U postgres postgres > /var/dump/sm4_db_$(date +%y-%m-%d_%H:%M:%S).sql"
              volumeMounts:
                - name: dump-volume
                  mountPath: /var/dump
              resources:
                limits:
                  cpu: 200m
                  memory: 64Mi
                requests:
                  cpu: 100m
                  memory: 32Mi
          restartPolicy: Never
          volumes:
            - name: dump-volume
              hostPath:
                path: $HOME/sm4-db-backup
