apiVersion: v1
kind: ConfigMap
metadata:
  name: sm4-db-credentials
  labels:
    app: sm4-db
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sm4-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sm4-db
  template:
    metadata:
      labels:
        app: sm4-db
    spec:
      containers:
        - name: sm4-db
          image: postgres:17.0-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: sm4-db-credentials
          volumeMounts:
            - name: db-volume
              mountPath: /var/lib/postgresql/data
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 32Mi
      volumes:
        - name: db-volume
          hostPath:
            path: $HOME/sm4-db
---
apiVersion: v1
kind: Service
metadata:
  name: sm4-db
  labels:
    app: sm4-db
spec:
  type: NodePort
  ports:
    - nodePort: 30001
      port: 5432
  selector:
    app: sm4-db
