apiVersion: batch/v1
kind: Job
metadata:
  name: sm4-db-migration-job
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      initContainers:
        - name: check-db-ready
          image: postgres:17.0-alpine
          command:
            - sh
            - -c
          args:
            - until pg_isready -h sm4-db -p 5432; do echo database is not ready; sleep 2; done;
          resources:
            limits:
              cpu: 200m
              memory: 32Mi
            requests:
              cpu: 100m
              memory: 16Mi
      containers:
        - name: migrate
          image: rtrzebinski/sm4:latest
          args: [ "migrate", "--path", "migrations", "--database", "postgres://postgres:postgres@sm4-db:5432/postgres?sslmode=disable", "up" ]
          resources:
            limits:
              cpu: 200m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 32Mi
      restartPolicy: Never
