apiVersion: batch/v1
kind: Job
metadata:
  name: sm4-migration-job
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
        - name: migrate
          image: rtrzebinski/sm4:latest
          args: [ "migrate", "--path", "migrations", "--database", "postgres://postgres:postgres@postgresdb:5432/postgres?sslmode=disable", "up" ]
      restartPolicy: Never
