apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-memorizer-4-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-memorizer-4-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: simple-memorizer-4-app
    spec:
      containers:
        - name: simple-memorizer-4
          image: "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
          ports:
            - name: app
              containerPort: 8000
              protocol: TCP
            - name: probes
              containerPort: 9090
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: 100Mi
              memory: 512Mi
            requests:
              cpu: 250m
              ephemeral-storage: 100Mi
              memory: 512Mi
          env:
            - name: DB_DSN
              value: "$DB_DSN"
---
apiVersion: v1
kind: Service
metadata:
  name: simple-memorizer-4-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: simple-memorizer-4-app
---
apiVersion: batch/v1
kind: Job
metadata:
  name: simple-memorizer-4-migration
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 1
  template:
    spec:
      containers:
        - name: migrate
          image: "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
          args: [ "migrate", "--path", "migrations", "--database", "$DB_DSN", "up" ]
      restartPolicy: Never
