apiVersion: batch/v1
kind: Job
metadata:
  name: sm4-db-migration-job
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: [ "sh", "-c", "until nc -z sm4-db 5432 > /dev/null; do echo waiting for sm4-db.; sleep 1; done;" ]
      containers:
        - name: migrate
          image: rtrzebinski/sm4:latest
          args: [ "migrate", "--path", "migrations", "--database", "postgres://postgres:postgres@sm4-db:5432/postgres?sslmode=disable", "up" ]
      restartPolicy: OnFailure
