apiVersion: apps/v1
kind: Deployment
metadata:
  name: sm4-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sm4-web
  template:
    metadata:
      labels:
        app: sm4-web
    spec:
      containers:
        - name: sm4-web
          image: rtrzebinski/sm4:latest
          imagePullPolicy: Always
          args: [ "/app/bin/simple-memorizer" ]
          ports:
            - containerPort: 8000
          env:
            - name: DB_DSN
              value: "postgres://postgres:postgres@sm4-postgresdb:5432/postgres?sslmode=disable"
---
apiVersion: v1
kind: Service
metadata:
  name: sm4-lb
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 8000
  selector:
    app: sm4-web
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sm4-db-secret-credentials
  labels:
    app: sm4-postgresdb
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sm4-postgresdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sm4-postgresdb
  template:
    metadata:
      labels:
        app: sm4-postgresdb
    spec:
      containers:
        - name: sm4-postgresdb
          image: postgres
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: sm4-db-secret-credentials
          volumeMounts:
            - name: db-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-volume
          hostPath:
            path: $HOME/sm4-db
---
apiVersion: v1
kind: Service
metadata:
  name: sm4-postgresdb
  labels:
    app: sm4-postgresdb
spec:
  type: NodePort
  ports:
    - nodePort: 30001
      port: 5432
  selector:
    app: sm4-postgresdb
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sm4-migration-job
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
        - name: migrate
          image: rtrzebinski/sm4:latest
          args: [ "migrate", "--path", "migrations", "--database", "postgres://postgres:postgres@sm4-postgresdb:5432/postgres?sslmode=disable", "up" ]
      restartPolicy: OnFailure
