apiVersion: apps/v1
kind: Deployment
metadata:
  name: sm4-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sm4-web
  template:
    metadata:
      labels:
        app: sm4-web
    spec:
      containers:
        - name: sm4-web
          image: rtrzebinski/sm4:latest
          imagePullPolicy: Always
          args: [ "/app/bin/simple-memorizer" ]
          ports:
            - containerPort: 8000
          env:
            - name: DB_DSN
              value: "postgres://postgres:postgres@sm4-db:5432/postgres?sslmode=disable"
---
apiVersion: v1
kind: Service
metadata:
  name: sm4-web
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 8000
  selector:
    app: sm4-web
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sm4-db-credentials
  labels:
    app: sm4-db
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sm4-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sm4-db
  template:
    metadata:
      labels:
        app: sm4-db
    spec:
      containers:
        - name: sm4-db
          image: postgres
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: sm4-db-credentials
          volumeMounts:
            - name: db-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-volume
          hostPath:
            path: $HOME/sm4-db
---
apiVersion: v1
kind: Service
metadata:
  name: sm4-db
  labels:
    app: sm4-db
spec:
  type: NodePort
  ports:
    - nodePort: 30001
      port: 5432
  selector:
    app: sm4-db
