apiVersion: apps/v1
kind: Deployment
metadata:
  name: sm4-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sm4-web
  template:
    metadata:
      labels:
        app: sm4-web
    spec:
      containers:
        - name: sm4-web
          image: rtrzebinski/sm4:latest
          imagePullPolicy: Always
          args: [ "/app/bin/simple-memorizer" ]
          ports:
            - containerPort: 8000
          env:
            - name: DB_DSN
              value: "postgres://postgres:postgres@sm4-db:5432/postgres?sslmode=disable"
          readinessProbe:
            httpGet:
              path: /readyz
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: sm4-web
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 8000
  selector:
    app: sm4-web
