apiVersion: apps/v1
kind: Deployment
metadata:
  name: sm4-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sm4-web
  template:
    metadata:
      labels:
        app: sm4-web
    spec:
      containers:
        - name: sm4-web
          image: rtrzebinski/sm4-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DB_DSN
              value: "postgres://postgres:postgres@sm4-db:5432/postgres?sslmode=disable"
            - name: PUBSUB_EMULATOR_HOST
              value: "sm4-pubsub:8085"
            - name: PUBSUB_PROJECT_ID
              value: "sm4-project"
            - name: PUBSUB_TOPIC_ID
              value: "sm4-topic"
            - name: AUTH_SERVER_ADDRESS
              value: "sm4-auth:50051"
          readinessProbe:
            httpGet:
              path: /readyz
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 16Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sm4-web
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 8000
  selector:
    app: sm4-web
