name: Build and Deploy to GKE

concurrency: deploy

on:
  workflow_dispatch:

  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  DB_DSN: ${{ secrets.DB_DSN }}
  IMAGE: simple-memorizer-4
  GKE_CLUSTER: gke-cluster
  GKE_ZONE: us-east1
  DEPLOYMENT_NAME: simple-memorizer-4-app # update if changed in k8s/deployment.yaml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Build Docker image
        run: |-
          docker build --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" .

      - name: Configure Docker to use the gcloud command-line tool as a credential helper for authentication
        run: |-
          gcloud --quiet auth configure-docker          

      - name: Publish Docker image
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"      

      - name: Get the GKE credentials
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      - name: Install gke-gcloud-auth-plugin
        run: |-
          gcloud components install gke-gcloud-auth-plugin

      - name: Deploy to GKE cluster
        run: |-
          export PROJECT_ID="$PROJECT_ID"
          export DB_DSN="$DB_DSN"
          export IMAGE="$IMAGE"
          export GITHUB_SHA="$GITHUB_SHA"
          envsubst < k8s/deployment.yaml | kubectl apply -f -

      - name: Check deployment rollout status
        run: |-
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
